### ISSUE TITLE
Giving root privilege on Mac works when running script, but not working when trying the same with freezed .app

### ISSUE THREAD

**Issue by Sakelariev** [mherrmann/fbs#16] opened 2018-04-12 13:32 UTC
Michael, I first want to thank you again for making fbs possible and helping me convert my app to it. I have an issue with my frozen app. Since I’m trying to make an app that blocks certain websites using the hosts file (I’m doing it for Mac first) my app needs root privilege. I have added a function to my main.py script that relaunches the app/script with root privileges. It works when I run the app, but after I freeze it it doesn’t - it get’s stuck in a loop and just relaunches itself everytime asking for the password.

Here's my code for relaunching main.py : 

```
if getattr(sys, 'frozen', False):
    # If the application is run as a bundle, the pyInstaller bootloader
    # extends the sys module by a flag frozen=True and sets the app
    # path into variable _MEIPASS'.
    application_path = sys._MEIPASS
else:
    application_path = os.path.dirname(os.path.abspath(__file__))
    print(application_path)

def _elevate():
    """Elevate user permissions if needed"""
    if os.getuid() != 0:
        _mac_elevate()
    else:
        pass

def _mac_elevate():
    """Relaunch asking for root privileges."""
    print("Relaunching with root permissions")
    applescript = ('do shell script "python '+application_path+'/main.py"'
                   'with administrator privileges')
    exit_code_1 = subprocess.call(['osascript', '-e', applescript])
    sys.exit(exit_code_1)

if __name__ == '__main__':
    _elevate()
    appctxt = AppContext()
    exit_code = appctxt.run()
    sys.exit(exit_code)
```
This is the changed function (using sys.executable for relaunching) that I'm trying to get working when the app is freezed : 

```
def _mac_elevate():
    """Relaunch asking for root privileges."""
    print("Relaunching with root permissions")
    applescript = ('do shell script "open '+ sys.executable +'"'
                   'with administrator privileges')
    exit_code_1 = subprocess.call(['osascript', '-e', applescript])
    sys.exit(exit_code_1)
```

The whole code is in this repository - https://github.com/Sakelariev/information-diet/tree/master/Diet2

What am I doing wrong? Any help would be very appreciated :)

**Comment by mherrmann** [comment] 2018-04-13 12:03
Hi Ivaylo,

I'm sorry, I don't have experience with this and can't think of a solution off the top of my head. I'd suggest asking your question on StackOverflow. People there are usually very helpful. I'd be happy to help too, but am way too busy with other things at the moment.

I'll close this issue for now as I don't think it's really caused by fbs.

**Closed by mherrmann** 2018-04-13 12:03 UTC

**Comment by Sakelariev** [comment] 2018-04-13 12:26
Ok, Michael. Thanks, I'll try asking on StackOverflow :)
