### ISSUE TITLE
I'm having trouble making my source code work with fbs. I've walked through your manual and book, but I'm still having troubles loading in the UI and getting the program to work in general after starting the fbs project. Works fine before using fbs

### ISSUE THREAD

**Issue by ptjlabs** [mherrmann/fbs#142] opened 2019-08-30 18:32 UTC
```
from fbs_runtime.application_context.PyQt5 import ApplicationContext
import sys
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtWidgets import QApplication,QDialog
from PyQt5.uic import loadUi
from PyQt5 import QtGui
import requests
from xml.etree import ElementTree as ET
import time 





class NeuraDemo(QDialog):
    def __init__(self):
        super(NeuraDemo,self).__init__()
        loadUi('neuraDemoRequest.ui',self)
        self.setWindowTitle('SPRINT Debugger v1')
        self.pushButton.clicked.connect(self.on_pushButton_clicked)
        self.ipAddressField.setText('204.145.155.155')
        self.iconName = "icon-section_150x150.png"
        self.setWindowIcon(QtGui.QIcon(self.iconName))

    @pyqtSlot()
    def on_pushButton_clicked(self):

        printer_update = dict()

        def get_xml_filename(p):
            xfile = p.split('/')
            return xfile[-1]
        path='/OemsiMediapath/OemsiMediapathDyn.xml'
        url= self.ipAddressField.text()
        try:
            req = requests.get(f'http://{url}{path}')

            target_file = get_xml_filename(path)

                    #Save file to current directory
            with open(target_file,'wb') as xml_file:
                xml_file.write(req.content)
                

            tree = ET.parse(target_file)
            root = tree.getroot()
            namespace_container = {
                'ompdyn':'http://www.hp.com/schemas/imaging/con/ledm/oemsimediapathdyn/2008/03/21',
                'dd':'http://www.hp.com/schemas/imaging/con/dictionaries/1.0/',
            }

            for ns in root.findall('ompdyn:OemsiMediapathSettings',namespace_container):
                
                Gap = ns.find('ompdyn:OemRw14',namespace_container)
                self.dsid1.setText(Gap.text)

                cfa = ns.find('ompdyn:OemRw12',namespace_container)
                new_cfa = hex(int(cfa.text))
                new_cfa = new_cfa[2:]
                self.cfa_textEdit.setText(new_cfa)

                UnWinder = ns.find('ompdyn:OemRw13',namespace_container)
                self.dsid3.setText(UnWinder.text)

                Mark = ns.find('ompdyn:OemRw15',namespace_container)
                self.dsid2.setText(Mark.text)

            for ns1 in root.findall('ompdyn:OemsiMediapathInfo',namespace_container):
                for fw in ns1.findall('ompdyn:OemMediapathFirmwareVersion',namespace_container):
                    printer_version = fw.find('dd:Revision',namespace_container)
                    # print(printer_version.text)
                    self.printerVersion.setText(printer_version.text[11:])

            path_to_resource = '/DevMgmt/ProductConfigDyn.xml'
            new_request = requests.get(f'http://{url}{path_to_resource}')
            _target_file = get_xml_filename(path)

                    #Save file to current directory
            with open(_target_file,'wb') as xml_file:
                xml_file.write(new_request.content)
                

            tree = ET.parse(target_file)
            root = tree.getroot()
            _namespace_container = {
                'prdcfgdyn':'http://www.hp.com/schemas/imaging/con/ledm/productconfigdyn/2007/11/05',
                'dd':'http://www.hp.com/schemas/imaging/con/dictionaries/1.0/',
            }
            for ns2 in root.findall('prdcfgdyn:ProductInformation',_namespace_container):
                serial = ns2.find('dd:SerialNumber',_namespace_container)
                # print(serial.text)
                self.serial_textEdit.setText(serial.text)

            tree.write(target_file)
        except:
            print('Attempted to connect.')
            # time.sleep(3)
            # sys.exit()
            # print(req.text)




if __name__ == '__main__':
    neuraApplication = QApplication([])
    # appctxt = ApplicationContext()
    widget=NeuraDemo()
    widget.show()
    sys.exit(neuraApplication.exec_())

```

**Comment by ptjlabs** [comment] 2019-08-30 18:41
The UI file is in the correct directory ".../main/resources/base/<file>"

**Comment by mherrmann** [comment] 2019-09-02 07:43
Hi,

thank you for getting my book. Unfortunately, the way in which you created this issue makes it difficult if not impossible for me to help you.

1) The title `I'm having trouble making my source code work with fbs. I've walked ...` is way too long. Just compare it to other people's issues:

![image](https://user-images.githubusercontent.com/1076393/64097603-002f4680-cd65-11e9-8adc-fb587e9c7af4.png)

2) You don't attach the UI file. How am I supposed to run your code? Not that I would want to, see below.

3) You don't tell me which error you're getting. How am I supposed to know what's not working? All you're saying is "I'm having trouble". I have zero means to even try to understand what the problems you are experiencing are.

4) Many people ask me for help. If I debugged through everybody's scripts, then I wouldn't have time to do anything else in my life. So you can't send me your scripts and say "Michael, help me please". I just don't have the time.

5) What I am here for is to find and fix bugs in fbs. If you can prove to me that the behavior you are seeing is a problem where fbs behaves in a way it shouldn't, then I am interested. But even then, I need a **minimal** example script that reproduces the problem. Any, even tiny, bits of code that are not relevant to the problem make me think "this person did not take the time to make it easy for me. So why should I take the time to help them?". So: Reduce your problem. Simplify your code, remove functionality from both your `.py` and `.ui` files until you've either found the root cause of the problem, or are convinced it's a bug in fbs.

6) Right now, I feel like your question is not about a "bug in fbs", but "help me fix my script". For this, I'd ask that you please pose your question on [StackOverflow](https://stackoverflow.com), as this is the appropriate place for such questions.

I'm closing this issue, also because the long titles make it such a mess. Feel free to re-open a new one if you have found a genuine bug in fbs, or would like to request a feature that may be useful for other fbs users.

**Closed by mherrmann** 2019-09-02 07:43 UTC
