### ISSUE TITLE
keyring package not supported?

### ISSUE THREAD

**Issue by kkagill** [mherrmann/fbs#187] opened 2020-03-31 00:24 UTC
Hello Michael,

Thanks for your work. I'm trying to use a [module](https://github.com/jaraco/keyring) from `pip install keyring` which was first released in 2009 and is still in use by many programmers.

My problem is simple. After `fbs freeze`, the program opens with **failed to execute script main** and I'm pretty sure fbs somehow crashes with this module.

```
from fbs_runtime.application_context.PyQt5 import ApplicationContext
from PyQt5.QtWidgets import QMainWindow

import sys
import keyring

keyring.set_password("system", "username", "password")    
print(keyring.get_password("system", "password"))

if __name__ == '__main__':
    appctxt = ApplicationContext()       # 1. Instantiate ApplicationContext
    window = QMainWindow()
    window.resize(250, 150)
    window.show()
    exit_code = appctxt.app.exec_()      # 2. Invoke appctxt.app.exec_()
    sys.exit(exit_code)
```
I know you are busy and just don't have time to look into this, but I'm giving you some heads up.
Thanks.

Windows 10 Pro
Python 3.6.8 64-bit
pip install fbs PyQt5==5.9.2

**Comment by datluu-dev** [comment] 2020-04-29 13:27
Yes, I am experiencing with the same issue, i have also checked the log from `fbs freeze --debug`, there is no traceback or any problems.

MacOS 10.15.4
Python 3.6.6rc1
PyInstaller==3.4
PyQt5==5.14.2

On the window 10 the debug log said this:
`PermissionError: [WinError 5] Access is denied: '...\\Desktop\\codeplace\\test-fbs\\target\\MyApp`

`subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'MyApp', '--noupx', '--log-level', 'DEBUG', '--noconfirm', '--icon', '...\\Desktop\\codeplace\\test-fbs\\src\\main\\icons\\Icon.ico', '--distpath', '...\\Desktop\\codeplace\\test-fbs\\target', '--specpath', 'C:\\Users\\Dat Luu\\Desktop\\codeplace\\test-fbs\\target\\PyInstaller', '--workpath', '...\\Desktop\\codeplace\\test-fbs\\target\\PyInstaller', '--additional-hooks-dir', '...\\virtual-envs\\wfh-client-env\\lib\\site-packages\\fbs\\freeze\\hooks', '--debug', 'all', '--runtime-hook', '...\\Desktop\\codeplace\\test-fbs\\target\\PyInstaller\\fbs_pyinstaller_hook.py', '...\\Desktop\\codeplace\\test-fbs\\src\\main\\python\\main.py']' returned non-zero exit status 1.`

I suggest we use something like [crypto library](https://pypi.org/project/pycrypto/) to encrypt the file with username and password

**Comment by mherrmann** [comment] 2020-05-01 10:19
If I understand this correctly, then it is a problem with the combination of `keyring` and `fbs`. fbs handles dependencies via PyInstaller, and such dependency problems thus need to be fixed in PyInstaller. So I'd ask that you please look for PyInstaller-related solutions to this problem.

**Closed by mherrmann** 2020-05-01 10:19 UTC

**Comment by datluu-dev** [comment] 2020-05-07 11:08
Many thanks, i have found the solution in this link

The problem is that keyring import every single os system backends when it packages with PyInstaller

Everything works with keyring==18.0.0.

Here is my approach for this issue:
`if sys.platform == 'darwin': # For MacOS
    import keyring.backends.OS_X
    keyring.set_keyring(keyring.backends.OS_X.Keyring())
elif sys.platform == 'linux2': # For Linux
    import keyring.backends.SecretService
    keyring.set_keyring(keyring.backends.SecretService.Keyring())
else:
    import keyring.backends.Windows # For Windows
    keyring.set_keyring(keyring.backends.Windows.WinVaultKeyring())`
